[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
note_taker = "EPJ35rHAvSfuyLCMt3S6x6J94NsqczkwbCeHn5JwwbMw"
notes = "3GqiCcr5K9GngBrMw6GzAR9VGFSe4dA5vThdzGHAXxdk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/psalmuel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
