[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_program = "21v5nvvE8EaB4JasoKP4f3Pr492oXwi8coFt1UB54qyQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/psalmuel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
